# List VS Numpy

In [1]:
a1 = [1,2,3,4,5,6,7,8,9,10]
print(a1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [2]:
# to get the sq of every element in the list
a1*a1

TypeError: can't multiply sequence by non-int of type 'list'

In [3]:
# using for loop
for i in a1:
    print(i*i)

1
4
9
16
25
36
49
64
81
100


In [4]:
# using list comprehension
a2 = [i*i for i in a1]
a2

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [5]:
import numpy as np

In [6]:
# converting the list into array
print(a1)
print(type(a1))
arr1 = np.array(a1)
print(arr1)
print(type(arr1)) #ndarray  : n dim array 

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
<class 'list'>
[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [7]:
5**2

25

In [8]:
5**3

125

In [9]:
print(arr1**2)

[  1   4   9  16  25  36  49  64  81 100]


In [10]:
arr1**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [11]:
# 1. can perform elementwise operations
# 2. faster than list operations

In [12]:
a1  = list(range(100000))

In [13]:
%timeit [i*i for i in a1]

8.37 ms ± 357 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [14]:
# usin NUmpy

In [15]:
arr2  = np.array(a1)

In [16]:
%timeit (arr2**2)

98.8 µs ± 3.57 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [17]:
# why faster ? it is  written C language