In [3]:
import numpy as np

In [4]:
a1 = [1,2,3,4,5,6,7]
a1

[1, 2, 3, 4, 5, 6, 7]

In [6]:
arr1 = np.array([1,2,3,4,5,6,7])
arr1

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
# array supports elementwise operation

In [8]:
print(type(arr1))

<class 'numpy.ndarray'>


#  1D Array

In [9]:
print(arr1.ndim)

1


In [10]:
print(arr1.shape) # (x_axis,y_axis) (0th,1st) (rows,coln)

(7,)


In [11]:
print(arr1.size) #total number of elements inside the array

7


In [14]:
arr2 = np.array(['A', 'B', 'C', 'D', 'E', 'F'])
arr2

array(['A', 'B', 'C', 'D', 'E', 'F'], dtype='<U1')

In [17]:
# attributes of arr2
# dim
print(arr2.ndim)
# shape
print(arr2.shape)
# size
print(arr2.size)

1
(6,)
6


# 1D Array creation

In [18]:
# by passing a list 
# using arange() method
# using linspace

In [21]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
list(range(1,10)) #last ement is not included

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [26]:
list(range(1,10,0.5))

TypeError: 'float' object cannot be interpreted as an integer

In [19]:
arr3 = np.arange(10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr3 = np.arange(1,10)#last ement is not included
arr3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr3 = np.arange(1,10,2)
arr3

array([1, 3, 5, 7, 9])

In [27]:
arr3 = np.arange(1,10,0.5)#step size in fraction is allowed in aranage() method
arr3

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [28]:
# attributes of arr2
# dim
print(arr3.ndim) #1D
# shape
print(arr3.shape) #(x,y) > (18,)
# size
print(arr3.size)#

1
(18,)
18


In [29]:
# using linspace
arr4 = np.linspace(1,10,18) #the element is included
arr4

array([ 1.        ,  1.52941176,  2.05882353,  2.58823529,  3.11764706,
        3.64705882,  4.17647059,  4.70588235,  5.23529412,  5.76470588,
        6.29411765,  6.82352941,  7.35294118,  7.88235294,  8.41176471,
        8.94117647,  9.47058824, 10.        ])

In [30]:
# attributes of arr2
# dim
print(arr4.ndim) #1D
# shape
print(arr4.shape) #(x,y) > (18,)
# size
print(arr4.size)#

1
(18,)
18


In [34]:
# using linspace
arr4 = np.linspace(1,10,19) #the element is included
arr4

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])