In [1]:
import numpy as np

In [2]:
a =  [1,2,3,4,5]
arr1 = np.array(a)

In [3]:
arr1

array([1, 2, 3, 4, 5])

# 2D Array creation


In [4]:
# usng list

In [5]:
m = [[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]]

In [6]:
m

[[1, 2, 3, 4, 5, 6, 7, 8], [1, 2, 3, 4, 5, 6, 7, 8]]

In [7]:
arr2 = np.array(m)
arr2

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [8]:
arr2.ndim

2

In [9]:
arr2.shape

(2, 8)

In [14]:
arr2.size

16

In [10]:
# using aranage() and reshape()

In [19]:
arr3  = np.arange(12)
print(arr3)
print(arr3.ndim)
print(arr3.shape)
print(arr3.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
1
(12,)
12


In [20]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [22]:
# reshaping the array ()
arr3.reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [23]:
arr3.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
arr3.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
arr3.reshape(3,4) # (rows,col) : rows * coln = total no of elements =  size of the array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
arr3.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [27]:
arr3.reshape(1,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [28]:
arr3.reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [37]:
arr3.dtype

dtype('int32')

In [30]:
arr4 = np.linspace(1,10,15)
arr4.reshape(5,3)

array([[ 1.        ,  1.64285714,  2.28571429],
       [ 2.92857143,  3.57142857,  4.21428571],
       [ 4.85714286,  5.5       ,  6.14285714],
       [ 6.78571429,  7.42857143,  8.07142857],
       [ 8.71428571,  9.35714286, 10.        ]])

In [32]:
# reshaping the array in single command
arr4 = np.linspace(1,10,15).reshape(5,3)
arr4

array([[ 1.        ,  1.64285714,  2.28571429],
       [ 2.92857143,  3.57142857,  4.21428571],
       [ 4.85714286,  5.5       ,  6.14285714],
       [ 6.78571429,  7.42857143,  8.07142857],
       [ 8.71428571,  9.35714286, 10.        ]])

In [36]:
arr4.dtype

dtype('float64')

In [33]:
b  = [1,2,3,4,'a','b','c','d']
arr5 = np.array(b)
print(arr5)

['1' '2' '3' '4' 'a' 'b' 'c' 'd']


In [34]:
arr5

array(['1', '2', '3', '4', 'a', 'b', 'c', 'd'], dtype='<U11')

In [35]:
arr5.dtype

dtype('<U11')

In [39]:
arr3.shape

(12,)

# If one unknown dimension

In [42]:
arr3.reshape(6,-1) # shape  =  12 , rows = 6 ,coln  = ? : if one of the values is dummy , it will be calculated and replaced by numpy

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [44]:
arr3.reshape(-6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [45]:
arr3.reshape(-6,-3)

ValueError: can only specify one unknown dimension