In [ ]:
# revision

In [ ]:
2D Array creation
# using aranage() and reshape()

In [3]:
import numpy as np

In [5]:
x = [[1,2,3],[3,4,5]]
arr1 = np.array(x)
print(arr1)

[[1 2 3]
 [3 4 5]]


In [12]:
print(list(range(10)))
print(list(range(1,10,2)))


print(np.arange(10))
print(np.arange(1,10,0.5))


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[1, 3, 5, 7, 9]
[0 1 2 3 4 5 6 7 8 9]
[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [14]:
arr2 = np.arange(1,10,0.5)
arr2.ndim

1

In [15]:
arr2.shape

(18,)

In [16]:
arr2.size

18

In [17]:
arr2.dtype

dtype('float64')

In [18]:
arr2.reshape(2,9)

array([[1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5]])

In [19]:
arr2.reshape(9,2)

array([[1. , 1.5],
       [2. , 2.5],
       [3. , 3.5],
       [4. , 4.5],
       [5. , 5.5],
       [6. , 6.5],
       [7. , 7.5],
       [8. , 8.5],
       [9. , 9.5]])

In [20]:
arr2.reshape(1,18) #column vector

array([[1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
        7.5, 8. , 8.5, 9. , 9.5]])

In [21]:
arr2.reshape(18,1) #row vector

array([[1. ],
       [1.5],
       [2. ],
       [2.5],
       [3. ],
       [3.5],
       [4. ],
       [4.5],
       [5. ],
       [5.5],
       [6. ],
       [6.5],
       [7. ],
       [7.5],
       [8. ],
       [8.5],
       [9. ],
       [9.5]])

In [22]:
arr2.reshape(9,-2)

array([[1. , 1.5],
       [2. , 2.5],
       [3. , 3.5],
       [4. , 4.5],
       [5. , 5.5],
       [6. , 6.5],
       [7. , 7.5],
       [8. , 8.5],
       [9. , 9.5]])

In [23]:
arr2.reshape(-9,-2)

ValueError: can only specify one unknown dimension

# Initial Placeholders

In [2]:
# zeros

In [24]:
np.zeros(4)

array([0., 0., 0., 0.])

In [25]:
np.zeros(3)

array([0., 0., 0.])

In [28]:
# np.zeros(rows,coln)
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.zeros([4,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# ones

In [26]:
np.ones(4)

array([1., 1., 1., 1.])

In [30]:
np.ones([2,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
# identiity matrix

In [31]:
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# diag

In [34]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# indexing and Slicing

In [ ]:
#  with 1d array

In [36]:
arr3 = np.arange(5,12)
arr3

array([ 5,  6,  7,  8,  9, 10, 11])

In [37]:
arr3[2] #7

7

In [38]:
arr3[6] #11

11

In [39]:
arr3[-1]# 11 , neg indexing also works here

11

In [41]:
# slicing in 1d 
# array[start:end] #last value is not included
arr3[1:3]

array([6, 7])

In [42]:
arr3[3:7]

array([ 8,  9, 10, 11])

In [ ]:
# it will take default start and end values , if lef blank !!

In [43]:
arr3[3:]

array([ 8,  9, 10, 11])

In [44]:
arr3[:5]

array([5, 6, 7, 8, 9])

In [ ]:
# with 2d arrays

# Slicing