# indexing and Slicing

In [1]:
# 2D Array

In [2]:
import numpy as np

In [9]:
arr1 = np.arange(5,15)


In [10]:
arr1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
arr1[2]

7

In [12]:
arr1[5]

10

In [13]:
arr1[3:8]

array([ 8,  9, 10, 11, 12])

In [14]:
arr1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
arr1[3:8:2]

array([ 8, 10, 12])

In [16]:
arr1[::-1]

array([14, 13, 12, 11, 10,  9,  8,  7,  6,  5])

# 2d

In [18]:
arr2 = np.arange(15).reshape(5,3)

In [19]:
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [20]:
arr2[0]

array([0, 1, 2])

In [21]:
arr2[3]

array([ 9, 10, 11])

In [22]:
arr2[0:3]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [23]:
arr2[0:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
arr2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [28]:
arr2[0:2,0:2]

array([[0, 1],
       [3, 4]])

In [29]:
# arr2[rows,col]
# arr2[strat_rows:end_rows,start_col:end_col]
arr2[1:3,1:3]

array([[4, 5],
       [7, 8]])

In [31]:
arr2[1:3,1:]

array([[4, 5],
       [7, 8]])

# Indexing with Boolean value arrays

In [32]:
# Indexing with Boolean value arrays
# fancy masking
# boolean Masking

In [36]:
arr3 = np.arange(12)

In [37]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
print(10>5)

True


In [39]:
arr3 > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True])

In [40]:
arr3 > 10

array([False, False, False, False, False, False, False, False, False,
       False, False,  True])

In [41]:
arr3%2 ==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False])

In [42]:
arr3%3 ==0

array([ True, False, False,  True, False, False,  True, False, False,
        True, False, False])

In [43]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [44]:
arr3%2 ==0 and arr3%3 ==0

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [46]:
(arr3%2 ==0) & (arr3%3 ==0)

array([ True, False, False, False, False, False,  True, False, False,
       False, False, False])

In [47]:
(arr3%2 ==0) | (arr3%3 ==0)

array([ True, False,  True,  True,  True, False,  True, False,  True,
        True,  True, False])

In [50]:
arr3[(arr3%2 ==0) | (arr3%3 ==0)]

array([ 0,  2,  3,  4,  6,  8,  9, 10])

In [53]:
arr4 = arr3[arr3%2 ==0]

In [52]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [54]:
arr4

array([ 0,  2,  4,  6,  8, 10])

In [57]:
arr5 = np.arange(12).reshape(3,4)

In [58]:
arr5

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
arr5[arr3%2 ==0] #o/p will be 1D array 

array([ 0,  2,  4,  6,  8, 10])