# Slicing 2D array

In [2]:
import numpy as np

In [3]:
arr1 =  np.arange(25).reshape(5,5)

In [4]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# getting rows

In [5]:
arr1[1] #required 2nd row

array([5, 6, 7, 8, 9])

In [8]:
arr1[-1] # the last row
arr1[4] # the last row

array([20, 21, 22, 23, 24])

In [12]:
arr1[0:3]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
arr1[3:5]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
# getting columns

In [14]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
arr1[0,0]

0

In [18]:
arr1[0:5,0] #getting the 0th column

array([ 0,  5, 10, 15, 20])

In [ ]:
#getting the 2nd column

In [23]:
# arr1[rows, col]
print(arr1[0:5,2])
print(arr1[:,2])

[ 2  7 12 17 22]
[ 2  7 12 17 22]


In [24]:
print(arr1[0:2,3:5])

[[3 4]
 [8 9]]


In [25]:
print(arr1[2:4,1:3])

[[11 12]
 [16 17]]


# Indexing with Boolean arrays

In [26]:
arr2 = np.arange(5,25)

In [28]:
np.size(arr2)

20

In [29]:
arr2.size

20

In [30]:
arr2 = np.arange(5,25).reshape(5,4)

In [31]:
arr2

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [34]:
mask1 = arr2%5 == 0

In [36]:
mask2 = arr2%3 ==0

In [38]:
arr2[mask1 | mask2]

array([ 5,  6,  9, 10, 12, 15, 18, 20, 21, 24])

In [39]:
arr2[(mask1)] or arr2[( mask2)]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [40]:
arr2[(mask1)] |arr2[( mask2)] # no of elements in both are not same , in-compatible operation

ValueError: operands could not be broadcast together with shapes (4,) (7,) 

In [1]:
# /HW
1. # slice the array to get below name
s = np.array([['Priya', 'Rohit', 'Aryan'],
       ['Neha', 'Avni', 'Akash'],
       ['Arjun', 'Riya', 'Devanshi']])


1. 'Priya', 'Rohit', 'Aryan'
2. 'Riya','Devanshi'
3. 'Neha', 'Avni', 'Akash' 'Arjun', 'Riya', 'Devanshi'
4. 'Avni'
5. 'Neha'

2. Use masking to get the values
score = np.random.randint(10,100,15).reshape(5,3)
1. find all scores > 50
2. find all scores <35

SyntaxError: invalid syntax (3487268980.py, line 8)

# Universal function

In [41]:
a = np.array([11,22,33,44,55])
b = np.array([1,2,3,4,5])

In [42]:
a

array([11, 22, 33, 44, 55])

In [43]:
b

array([1, 2, 3, 4, 5])

In [44]:
a + b

array([12, 24, 36, 48, 60])

In [46]:
a = np.array([11,22,33,44,55])
b = np.array([1,2,3,4,7])
a + b 

array([12, 24, 36, 48, 62])

In [47]:
b - a

array([-10, -20, -30, -40, -48])

In [48]:
a * b

array([ 11,  44,  99, 176, 385])

In [57]:
a = np.array([11,0,33,44,55])
b = np.array([1,2,3,4,5])

In [58]:
b/a

C:\Users\RAHUL\AppData\Local\Temp\ipykernel_12748\2243761560.py:1: RuntimeWarning: divide by zero encountered in divide
  b/a


array([0.09090909,        inf, 0.09090909, 0.09090909, 0.09090909])