# Splitting

In [1]:
import numpy as np

In [2]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [3]:
np.split(a,3)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]

In [5]:
np.split(a,7) #equal division can be done only , else error

ValueError: array split does not result in an equal division

In [8]:
b = np.arange(16).reshape(4,4)

In [9]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
np.split(b,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [12]:
np.split(b,4,axis=0) #defaul axis is zero

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [13]:
np.split(b,4,axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [15]:
c = np.arange(9).reshape(3,3)
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
np.split(c,3,axis=0)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [17]:
np.split(c,3,axis=1)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [45]:
c

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [46]:
np.hsplit(c,3)

[array([[0],
        [3],
        [6]]),
 array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]])]

In [47]:
np.vsplit(c,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

# Aggreagte Function

In [18]:
a = np.array([11,22,33,44,55])
b = np.array([1,2,3,4,5])

In [19]:
# ufunc

In [20]:
a+b

array([12, 24, 36, 48, 60])

In [21]:
a-b

array([10, 20, 30, 40, 50])

In [22]:
a/b

array([11., 11., 11., 11., 11.])

In [24]:
a = np.array([11,0,33,44,55])
b = np.array([1,2,3,4,5])

In [25]:
a/b

array([11.,  0., 11., 11., 11.])

In [26]:
b/a #divide by zero is supported

C:\Users\RAHUL\AppData\Local\Temp\ipykernel_14080\2243761560.py:1: RuntimeWarning: divide by zero encountered in divide
  b/a


array([0.09090909,        inf, 0.09090909, 0.09090909, 0.09090909])

In [27]:
a = np.array([11,22,33,44,55])
b = np.array([1,2,3,4,5])

In [28]:
np.sum(a) #this will add all the elements inside the array 'a'

165

In [29]:
np.sum(b)

15

In [30]:
np.mean(a)

33.0

In [31]:
np.min(a)

11

In [32]:
np.max(a)

55

In [35]:
arr1 =  np.arange(10,60,2).reshape(5,5)
arr1

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

In [36]:
np.sum(arr1)

850

In [39]:
np.sum(arr1,axis=1)

array([ 70, 120, 170, 220, 270])

In [40]:
np.sum(arr1,axis=0)

array([150, 160, 170, 180, 190])

In [37]:
np.min(arr1)

10

In [41]:
np.min(arr1,axis=1)

array([10, 20, 30, 40, 50])

In [42]:
np.min(arr1,axis=0)

array([10, 12, 14, 16, 18])

In [43]:
arr1

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58]])

In [38]:
np.max(arr1)

58

In [44]:
np.max(arr1,axis=0)

array([50, 52, 54, 56, 58])