# Logical function

In [1]:
import numpy as np

In [2]:
# any
# all
# True / False

In [3]:
arr1 = np.array([11,22,33,44,0,1])

In [4]:
arr1

array([11, 22, 33, 44,  0,  1])

In [5]:
np.any(arr1)

True

In [6]:
arr2 = np.array([0,0,0,0,1])
arr2

array([0, 0, 0, 0, 1])

In [7]:
np.any(arr2)

True

In [8]:
arr3 = np.array([0,0,0,0,0])
arr3

array([0, 0, 0, 0, 0])

In [9]:
np.any(arr3)

False

In [12]:
arr2
np.all(arr2)

False

In [13]:
arr3
np.all(arr3)

False

In [14]:
arr4 = np.array([1,1,1,1,1,1])

In [15]:
arr4

array([1, 1, 1, 1, 1, 1])

In [16]:
np.all(arr4)

True

In [17]:
a =np.array([44,55])
b = np.array([1,2])

In [18]:
print(a)
print(b)

[44 55]
[1 2]


In [19]:
100>50

True

In [20]:
a > b

array([ True,  True])

In [21]:
np.any(a>b)

True

In [22]:
np.all(a>b)

True

In [24]:
a =np.array([44,55,66,77])
b = np.array([1,2,3,99])
a>b

array([ True,  True,  True, False])

In [25]:
np.any(a>b)

True

In [26]:
np.all(a>b)

False

# Sorting

In [31]:
c = np.array([44,55,11,22,77,88,10])

In [41]:
np.sort(c)

array([10, 11, 22, 44, 55, 77, 88])

In [42]:
np.argsort(c)

array([6, 2, 3, 0, 1, 4, 5], dtype=int64)

In [43]:
# np.sort(c,ascending=False) # no such paramter available in numpy

In [44]:
sorted_ans = np.sort(c)

In [45]:
sorted_ans

array([10, 11, 22, 44, 55, 77, 88])

In [46]:
descending_ans = sorted_ans[::-1]

In [47]:
descending_ans

array([88, 77, 55, 44, 22, 11, 10])

In [48]:
np.flip(sorted_ans)

array([88, 77, 55, 44, 22, 11, 10])

In [51]:
print(c)
np.flip(c) # to reverse the order as per index posn

[44 55 11 22 77 88 10]


array([10, 88, 77, 22, 11, 55, 44])

In [52]:
c

array([44, 55, 11, 22, 77, 88, 10])

In [53]:
print(c) 55 11 22 77 

[44 55 11 22 77 88 10]
