In [1]:
import numpy as np

In [2]:
# numpy support only homogenous data type

# Loading the raw data into numpy

In [3]:
data = np.loadtxt('fitbit.txt',dtype='str') #converintg all the elements into string data type

In [4]:
data

array([['06-10-2017', '5464', '200', '181', '6', '0', '68'],
       ['07-10-2017', '7167', '200', '208', '6', '0', '68'],
       ['08-10-2017', '9874', '300', '341', '5', '0', '68'],
       ['09-10-2017', '4969', '100', '190', '8', '0', '68'],
       ['10-10-2017', '8538', '300', '307', '5', '0', '68'],
       ['11-10-2017', '9875', '300', '302', '5', '0', '68'],
       ['12-10-2017', '4662', '100', '198', '8', '0', '68'],
       ['13-10-2017', '6310', '200', '201', '6', '0', '68'],
       ['14-10-2017', '7556', '200', '195', '6', '0', '68'],
       ['15-10-2017', '9073', '300', '327', '5', '0', '68'],
       ['16-10-2017', '9690', '300', '331', '5', '0', '68'],
       ['17-10-2017', '9146', '300', '318', '5', '0', '68'],
       ['18-10-2017', '9752', '300', '344', '5', '0', '68'],
       ['19-10-2017', '6974', '200', '204', '6', '0', '68'],
       ['20-10-2017', '5619', '200', '180', '6', '0', '68'],
       ['21-10-2017', '6889', '200', '201', '6', '0', '68'],
       ['22-10-2017', '8

In [5]:
print(data)

[['06-10-2017' '5464' '200' '181' '6' '0' '68']
 ['07-10-2017' '7167' '200' '208' '6' '0' '68']
 ['08-10-2017' '9874' '300' '341' '5' '0' '68']
 ['09-10-2017' '4969' '100' '190' '8' '0' '68']
 ['10-10-2017' '8538' '300' '307' '5' '0' '68']
 ['11-10-2017' '9875' '300' '302' '5' '0' '68']
 ['12-10-2017' '4662' '100' '198' '8' '0' '68']
 ['13-10-2017' '6310' '200' '201' '6' '0' '68']
 ['14-10-2017' '7556' '200' '195' '6' '0' '68']
 ['15-10-2017' '9073' '300' '327' '5' '0' '68']
 ['16-10-2017' '9690' '300' '331' '5' '0' '68']
 ['17-10-2017' '9146' '300' '318' '5' '0' '68']
 ['18-10-2017' '9752' '300' '344' '5' '0' '68']
 ['19-10-2017' '6974' '200' '204' '6' '0' '68']
 ['20-10-2017' '5619' '200' '180' '6' '0' '68']
 ['21-10-2017' '6889' '200' '201' '6' '0' '68']
 ['22-10-2017' '8616' '300' '329' '5' '0' '68']
 ['23-10-2017' '9131' '300' '315' '5' '0' '68']
 ['24-10-2017' '4211' '100' '197' '8' '0' '68']
 ['25-10-2017' '4291' '100' '184' '8' '0' '68']
 ['26-10-2017' '8569' '300' '328' '5' '0

# checking various parameters

In [6]:
data.shape

(26, 7)

In [7]:
data.size

182

In [8]:
data.ndim

2

In [9]:
data.dtype

dtype('<U10')

# Cheking the data

In [10]:
data[0]

array(['06-10-2017', '5464', '200', '181', '6', '0', '68'], dtype='<U10')

In [11]:
# transposing the data

In [12]:
data.T

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017'],
       ['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
        '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
        '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
        '6347', '5911'],
       ['200', '200', '300', '100', '300', '300', '100', '200', '200',
        '300', '300', '300', '300', '200', '200', '200', '300', '300',
        '100', '100', '300', '300', '300', '100', '200', '200'],
       ['181', '208', '341', '190', '307', '302', '198', '201', '195',
        '327', '331', '318', '344', '204', '180', '201', '32

In [13]:
data.T[0]


array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017'], dtype='<U10')

In [14]:
# packing and unpacking the data
date, step_count,mood,calories_burned,hours_of_sleep,bool_of_active,weight_kg = data.T

In [15]:
date

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017'], dtype='<U10')

In [16]:
step_count

array(['5464', '7167', '9874', '4969', '8538', '9875', '4662', '6310',
       '7556', '9073', '9690', '9146', '9752', '6974', '5619', '6889',
       '8616', '9131', '4211', '4291', '8569', '9337', '8475', '4510',
       '6347', '5911'], dtype='<U10')

In [17]:
step_count.dtype

dtype('<U10')

# converting various features into int dtype

In [18]:
step_count = np.array(step_count,dtype='int')

In [19]:
step_count

array([5464, 7167, 9874, 4969, 8538, 9875, 4662, 6310, 7556, 9073, 9690,
       9146, 9752, 6974, 5619, 6889, 8616, 9131, 4211, 4291, 8569, 9337,
       8475, 4510, 6347, 5911])

In [20]:
step_count.dtype

dtype('int32')

In [21]:
# mood = np.array(mood,dtype='int')
calories_burned = np.array(calories_burned,dtype='int')
hours_of_sleep = np.array(hours_of_sleep,dtype='int')

In [22]:
mood

array(['200', '200', '300', '100', '300', '300', '100', '200', '200',
       '300', '300', '300', '300', '200', '200', '200', '300', '300',
       '100', '100', '300', '300', '300', '100', '200', '200'],
      dtype='<U10')

In [23]:
mood.dtype

dtype('<U10')

In [24]:
# int(np.array(int(step_count))
# np.array()

In [25]:
data.shape

(26, 7)

In [26]:
# taking a closer look inside the mood column

In [27]:
mood.ndim

1

In [28]:
mood

array(['200', '200', '300', '100', '300', '300', '100', '200', '200',
       '300', '300', '300', '300', '200', '200', '200', '300', '300',
       '100', '100', '300', '300', '300', '100', '200', '200'],
      dtype='<U10')

In [29]:
# to get number of unique valus ?
np.unique(mood)

array(['100', '200', '300'], dtype='<U10')

In [30]:
'''
100 Sad
200 Neutral
300 happy
'''

'\n100 Sad\n200 Neutral\n300 happy\n'

In [31]:
# converting the numerical form to string format

In [35]:
mood == '100' #using this as mask

array([False, False, False,  True, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True,  True, False, False, False,  True, False, False])

In [37]:
mood[mood == '100']

array(['100', '100', '100', '100', '100'], dtype='<U10')

In [38]:
# now replacing the values 
mood[mood == '100'] = 'Sad'

In [39]:
mood

array(['200', '200', '300', 'Sad', '300', '300', 'Sad', '200', '200',
       '300', '300', '300', '300', '200', '200', '200', '300', '300',
       'Sad', 'Sad', '300', '300', '300', 'Sad', '200', '200'],
      dtype='<U10')

In [40]:
mood == '200'

array([ True,  True, False, False, False, False, False,  True,  True,
       False, False, False, False,  True,  True,  True, False, False,
       False, False, False, False, False, False,  True,  True])

In [41]:
mood[mood == '200']

array(['200', '200', '200', '200', '200', '200', '200', '200', '200'],
      dtype='<U10')

In [42]:
mood[mood == '200'] = 'Neutral'

In [43]:
mood

array(['Neutral', 'Neutral', '300', 'Sad', '300', '300', 'Sad', 'Neutral',
       'Neutral', '300', '300', '300', '300', 'Neutral', 'Neutral',
       'Neutral', '300', '300', 'Sad', 'Sad', '300', '300', '300', 'Sad',
       'Neutral', 'Neutral'], dtype='<U10')

In [44]:
mood[mood == '300'] = 'Happy'

In [45]:
mood

array(['Neutral', 'Neutral', 'Happy', 'Sad', 'Happy', 'Happy', 'Sad',
       'Neutral', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Neutral', 'Neutral', 'Neutral', 'Happy', 'Happy', 'Sad', 'Sad',
       'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral'],
      dtype='<U10')

In [46]:
np.unique(mood)

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

# working on step count

In [48]:
step_count

array([5464, 7167, 9874, 4969, 8538, 9875, 4662, 6310, 7556, 9073, 9690,
       9146, 9752, 6974, 5619, 6889, 8616, 9131, 4211, 4291, 8569, 9337,
       8475, 4510, 6347, 5911])

In [49]:
np.max(step_count)

9875

In [50]:
np.min(step_count)

4211

In [51]:
np.mean(step_count)

7344.461538461538

In [52]:
np.argmax(step_count) # the index position of the max val

5

In [53]:
# calling the data from dates corr to same index posn
date[5]

'11-10-2017'

In [54]:
date[np.argmin(step_count)]

'24-10-2017'

# freq of mood

In [55]:
mood

array(['Neutral', 'Neutral', 'Happy', 'Sad', 'Happy', 'Happy', 'Sad',
       'Neutral', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Neutral', 'Neutral', 'Neutral', 'Happy', 'Happy', 'Sad', 'Sad',
       'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral'],
      dtype='<U10')

In [56]:
# checking the count of each mood 

In [59]:
len(mood[mood == 'Sad'])

5

In [60]:
len(mood[mood == 'Neutral'])

9

In [62]:
len(mood[mood == 'Happy'])

12

In [64]:
np.unique(mood,return_counts=True)

(array(['Happy', 'Neutral', 'Sad'], dtype='<U10'),
 array([12,  9,  5], dtype=int64))

In [65]:
step_count[mood == 'Sad']

array([4969, 4662, 4211, 4291, 4510])

In [66]:
# taking mean of the step counts when the mood was "Sad"

np.mean(step_count[mood == 'Sad'])

4528.6

In [68]:
# taking mean of the step counts when the mood was "Neutral"

np.mean(step_count[mood == 'Neutral'])

6470.777777777777

In [69]:
# taking mean of the step counts when the mood was "Happy"

np.mean(step_count[mood == 'Happy'])

9173.0