In [ ]:
# /HW
1. # slice the array to get below name
s = np.array([['Priya', 'Rohit', 'Aryan'],
       ['Neha', 'Avni', 'Akash'],
       ['Arjun', 'Riya', 'Devanshi']])


1. 'Priya', 'Rohit', 'Aryan'
2. 'Riya','Devanshi'
3. 'Neha', 'Avni', 'Akash' 'Arjun', 'Riya', 'Devanshi'
4. 'Avni'
5. 'Neha'

2. Use masking to get the values
score = np.random.randint(10,100,15).reshape(5,3)
1. find all scores > 50
2. find all scores <35

# Broadcasting

In [2]:
import numpy as np

In [3]:
x = np.array([10,20,30]) #list  =  1D Array 
y = np.array([[1],[2],[3],[4]]) #list of list = 2D array

In [4]:
x

array([10, 20, 30])

In [5]:
y

array([[1],
       [2],
       [3],
       [4]])

In [7]:
print(x.ndim)
print(x.shape)
print(y.ndim)
print(y.shape)

1
(3,)
2
(4, 1)


In [8]:
x + y

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33],
       [14, 24, 34]])

In [11]:
x

array([10, 20, 30])

In [10]:
x +1

array([11, 21, 31])

In [15]:
x = np.array([10,20,30,40]) #list  =  1D Array 
y = np.array([[1],[2],[3],[4]]) #list of list = 2D array

In [16]:
x

array([10, 20, 30, 40])

In [17]:
y

array([[1],
       [2],
       [3],
       [4]])

In [18]:
x+y

array([[11, 21, 31, 41],
       [12, 22, 32, 42],
       [13, 23, 33, 43],
       [14, 24, 34, 44]])

In [22]:
x = np.array([10,20,30]) #list  =  1D Array 

In [23]:
arr1 = np.arange(15).reshape(5,3)

In [24]:
arr1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [25]:
arr1 +x

array([[10, 21, 32],
       [13, 24, 35],
       [16, 27, 38],
       [19, 30, 41],
       [22, 33, 44]])

In [ ]:
# splitting

In [26]:
x = np.arange(9)

In [27]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [28]:
np.split(x,3) #the o/p will be a list of arrays

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [29]:
np.split(x,3)[0]

array([0, 1, 2])

In [30]:
z = np.arange(16).reshape(4,4)

In [31]:
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [32]:
np.split(z,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [34]:
np.split(z,4,axis=0)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [35]:
np.split(z,4,axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
# hsplit
# vsplit


In [ ]:
# Aggreagte Function